sudo: required
services:
  - docker
before_install:
  - docker build -t production/react -f Dockerfile.dev .

script:
  - docker run -e CI=true production/react npm run test

deploy:
    provider: elasticbeantalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-556406167639"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: 
      secure: "$AWS_ACCESS_KEY"
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"

